services:
  dads-database:
    build: ./dockerfiles
    image: dads-database-image:latest
    container_name: dads-database-container
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data1
    ports:
      - "5432:5432" 

volumes:
  postgres_data: